sonar.projectKey=PlumiaUnlam_plumia-frontend
sonar.organization=plumiaunlam
sonar.projectName=PlumIA Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=app,components,helpers,lib
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.d.ts

sonar.tests=app,components,helpers,lib
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
